# Generated by jPipe, then filled in by hand.
# Source : deployable.jd
#
# jpipe process -f python -i deployable.jd -m deployable -o deployable.py
#
# One function per element of the `deployable` model, tied to its element by
# @jpipe_link("deployable:<id>"). The conclusion has no function: the runner passes it as
# soon as everything under it passes.
#
# The numbers are model C from the case study, held to the 80% bar it agreed to. Nothing
# here needs a classifier, and only the standard library is imported.

from typing import Any, Callable

from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
from jpipe_runner.framework.decorators.link_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]

###                               ###
## Mocked valued for demo purposes ##
###                               ###

MEASURED_ACCURACY = 0.818  # What the run measured
AGREED_BAR = 0.80          # the bar it was agreed against.

###          ###
## deployable ##
###          ###

@jpipe_link("deployable:agreed")
@jpipe(produce=["agreed_bar"])
def a_performance_threshold_is_agreed_upon_80(produce: JpipeProduce) -> bool:
    """[evidence] A performance threshold is agreed upon (80%)"""
    produce("agreed_bar", AGREED_BAR)
    return True


@jpipe_link("deployable:model")
@jpipe(produce=["trained_model"])
def the_model_is_available(produce: JpipeProduce) -> bool:
    """[evidence] The model is available"""
    # Real code goes here (file exists, load file, ...)
    produce("trained_model", "emotion-classifier-c")
    return True


@jpipe_link("deployable:test_ds")
@jpipe(produce=["dataset"])
def the_test_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] The test dataset is available"""
    produce("dataset", "test-split")
    return True


@jpipe_link("deployable:execution")
@jpipe(produce=["measured_accuracy"], consume=["trained_model", "dataset"])
def run_the_model_on_the_dataset(trained_model, dataset,
                                 produce: JpipeProduce) -> bool:
    """[strategy] Run the model on the dataset"""
    # A run needs both of the things below it, and produces the measurement the argument
    # is about. It reads no bar: whether the number is good enough is not its call.
    if not (trained_model and dataset):
        return False
    produce("measured_accuracy", MEASURED_ACCURACY)
    return True


@jpipe_link("deployable:threshold")
@jpipe(consume=["measured_accuracy", "agreed_bar"])
def confirm_the_report_s_measurements_meet_the_agreed_threshold(measured_accuracy,
                                                               agreed_bar) -> bool:
    """[strategy] Confirm the report's measurements meet the agreed threshold"""
    # The one judgement in the argument: a measured number, and the bar it was agreed
    # against, each arriving from the element that establishes it.
    return measured_accuracy >= agreed_bar


# The runner passes this claim through unless it is bound. Uncomment to check it.
# @jpipe_link("deployable:reporting")
# @jpipe(produce=[], consume=[])
# def a_performance_report_is_available(produce: JpipeProduce) -> bool:
#     """[sub-conclusion] A performance report is available"""
#     pass
