# Generated by jPipe
# Source : deployable.jd
# Date   : 2026-08-12T21:45:21.816313Z

from typing import Any, Callable
from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
from jpipe_runner.framework.decorators.link_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]

####      ####
## Evidence ##
####      ####

@jpipe_link("deployable:model")
@jpipe(produce=["model"])
def the_model_is_available(produce: JpipeProduce) -> bool:
    """[evidence] the model is available"""
    produce("model", True)
    return True

@jpipe_link("deployable:training_ds")
@jpipe(produce=["training_ds"])
def the_training_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] the training dataset is available"""
    produce("training_ds", True)
    return True

####        ####
## Strategies ##
####        ####

@jpipe_link("deployable:execution")
@jpipe(produce=["report"], consume=["model", "training_ds"])
def executing_the_model_on_the_dataset(model, training_ds, 
                                       produce: JpipeProduce) -> bool:
    """[strategy] executing the model on the dataset"""
    produce("report", True)
    return model and training_ds

@jpipe_link("deployable:threshold")
@jpipe(produce=[], consume=["report"])
def confront_the_report_s_measurements_to_the_80_bar(report,
                                                     produce: JpipeProduce) -> bool:
    """[strategy] Confront the report's measurements to the 80% bar"""
    return report



####                        ####
## Sub-conclusions (optional) ##
####                        ####

@jpipe_link("deployable:reporting")
@jpipe(produce=[], consume=[])
def a_report_is_available(produce: JpipeProduce) -> bool:
    """[sub-conclusion] a report is available"""
    return True
